# MNE-Python Basic Preprocess
https://mne.tools/stable/documentation/index.html

In [1]:
import pyxdf
import mne
import numpy as np
import pandas as pd
streams, header = pyxdf.load_xdf("C:/Users/Toey/Desktop/data_ssvep/Toey/exp1/block_2.xdf")
# streams, header = pyxdf.load_xdf("Pipo_1_5_test1.xdf") #Example Data from Lab Recoder
# streams, header = pyxdf.load_xdf("C:/Users/Toey/Desktop/SSVEP_data/sub-P001/ses-S001/eeg/sub-P001_ses-S001_task-Default_run-001_eeg.xdf") #Example Data from Lab Recoder

In [2]:
streams

[{'info': defaultdict(list,
              {'name': ['obci_eeg1'],
               'type': ['EEG'],
               'channel_count': ['8'],
               'nominal_srate': ['250'],
               'channel_format': ['float32'],
               'source_id': ['openbcigui'],
               'version': ['1.1000000000000001'],
               'created_at': ['97866.327942699994'],
               'uid': ['2e5886a9-33e7-4ade-be69-41ca8fd3a01e'],
               'session_id': ['default'],
               'hostname': ['DESKTOP-5KJIQRK'],
               'v4address': [None],
               'v4data_port': ['16572'],
               'v4service_port': ['16572'],
               'v6address': [None],
               'v6data_port': ['16572'],
               'v6service_port': ['16572'],
               'desc': [None],
               'stream_id': 1,
               'effective_srate': 250.3560058307626}),
  'footer': {'info': defaultdict(list,
               {'first_timestamp': ['101410.7625467'],
                'last_

In [3]:
raw_data = streams[0]["time_series"].T #From Steam variable this query is EEG data

In [4]:
raw_data.shape # It contain with 8 channel of EGG data

(8, 229960)

In [5]:
channels =['Fz','Cz','P4','Pz','P3','P08','Oz','P07'] #Set your target EEG channel name
info = mne.create_info(
    ch_names= channels,
    ch_types= ['eeg']*len(channels),
    sfreq= 250 #OpenBCI Frequency acquistion
)
# Create MNE rawarray
raw_mne = mne.io.RawArray(raw_data, info, verbose=False)

In [6]:
raw_mne = mne.io.RawArray(raw_data, info, verbose=False)
print(raw_mne)
event_index = streams[1]["time_series"].T[0] #Get all event marker of experiment 
#.T คือ transpose array [0] data ใน column 0 ของ streams[1]["time_series"]
print(event_index.shape)
event_timestamp = streams[1]["time_stamps"].T #Timestamp when event marked
# รับเวลาที่ marker นั้นอยู่
print(event_timestamp.shape)

<RawArray | 8 x 229960 (919.8 s), ~14.0 MB, data loaded>
(180,)
(180,)


# Create MNE Epoch

In [7]:
# event_index = streams[1]["time_series"].T[0] #Get all event marker of experiment 
# event_timestamp = streams[1]["time_stamps"].T #Timestamp when event marked

In [8]:
event_index

array([1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0,
       3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0,
       0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2,
       0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4,
       0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0,
       2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0,
       4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1,
       0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3,
       0, 4, 0, 4])

In [9]:
event_timestamp

array([101412.66178168, 101417.69990878, 101422.68731458, 101427.71865808,
       101432.71048638, 101437.77358667, 101442.74343677, 101447.79814917,
       101452.77334647, 101457.77383687, 101462.81027607, 101467.79805217,
       101472.83819336, 101477.82699206, 101482.85060056, 101487.84395496,
       101492.88016346, 101497.87060336, 101502.87099786, 101507.89227475,
       101512.88187595, 101517.92605795, 101522.91492175, 101527.93306355,
       101532.92164605, 101537.94726004, 101542.93828464, 101547.93862004,
       101552.95582554, 101557.94511934, 101562.99518184, 101567.96353384,
       101572.99045423, 101577.98103103, 101582.99780143, 101587.98478703,
       101592.98509123, 101598.00252833, 101602.99908473, 101608.02674492,
       101613.01724792, 101618.03688472, 101623.03107722, 101628.05803722,
       101633.04976322, 101638.05006101, 101643.08593241, 101648.07395831,
       101653.10295661, 101658.09139281, 101663.12206321, 101668.11039421,
       101673.1384465 , 1

In [10]:
events = np.column_stack((np.array(event_timestamp, dtype = int),
                        np.zeros(len(event_timestamp), dtype = int),
                        np.array(event_index, dtype = int)))
fre1 = 8
fre2 = 10
fre3 = 12
fre4 = 14
events_id = { # Set up your event name
     f'natural': 0,
     f'Frequency {fre1} Hz': 1,
     f'Frequency {fre2} Hz': 2,
     f'Frequency {fre3} Hz': 3,
     f'Frequency {fre4} Hz': 4,
}
# events_id = { # Set up your event name
#      f'Frequency {fre1} Hz': 1,
#      f'Frequency {fre2} Hz': 2,
#      f'Frequency {fre3} Hz': 3,
#      f'Frequency {fre4} Hz': 4,
# }

mne_epochs = mne.Epochs(raw_mne, events, 
        tmin= -0.5,     # init timestamp of epoch (0 means trigger timestamp same as event start)
        tmax= 10,    # final timestamp (10 means set epoch duration 10 second)
        event_id =events_id,
        preload = True,
        event_repeated='drop',
        baseline=(-0.5, 0)
    )

Not setting metadata
180 matching events found
Applying baseline correction (mode: mean)
0 projection items activated
Using data from preloaded Raw for 180 events and 2626 original time points ...
0 bad epochs dropped


In [11]:
mne_epochs.get_data().shape

C:\Users\Toey\AppData\Local\Temp\ipykernel_11412\1290654083.py:1: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  mne_epochs.get_data().shape


(180, 8, 2626)

In [12]:
# import random
# natural_events = [event for event in events if event[2] == events_id['natural']]
# selected_natural_events = random.sample(natural_events, 11)
# print(selected_natural_events)

In [13]:
raw_data = mne_epochs.get_data()
y = mne_epochs.events[:, -1]
print(y.shape)

(180,)


C:\Users\Toey\AppData\Local\Temp\ipykernel_11412\3314739420.py:1: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  raw_data = mne_epochs.get_data()


In [14]:
dataset = mne_epochs.to_data_frame()
print(dataset.shape)

(472680, 11)


In [15]:
labels = mne_epochs.events[:,-1]
labels

array([1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0,
       3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0,
       0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2,
       0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4,
       0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0,
       2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0,
       4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1,
       0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 0, 1, 0, 2, 0, 3,
       0, 4, 0, 4])

In [16]:
dataset

time        condition  epoch            Fz            Cz  \
0       -0.500   Frequency 8 Hz      0  4.843635e+08 -1.771580e+08   
1       -0.496   Frequency 8 Hz      0  9.611350e+07 -5.813460e+07   
2       -0.492   Frequency 8 Hz      0 -4.827527e+08  1.306027e+08   
3       -0.488   Frequency 8 Hz      0 -4.428094e+08  1.295080e+08   
4       -0.484   Frequency 8 Hz      0  2.743235e+08 -5.111604e+07   
...        ...              ...    ...           ...           ...   
472675   9.984  Frequency 14 Hz    179 -3.079675e+08  4.269578e+06   
472676   9.988  Frequency 14 Hz    179 -8.165808e+08  2.326153e+08   
472677   9.992  Frequency 14 Hz    179 -2.148278e+08  3.086821e+07   
472678   9.996  Frequency 14 Hz    179  4.756185e+08 -2.818320e+08   
472679  10.000  Frequency 14 Hz    179  3.277610e+08 -2.778984e+08   

                  P4            Pz            P3           P08            Oz  \
0       5.988139e+09  5.878528e+08 -2.577135e+09  5.699618e+08  5.967600e+08   
1       5.391639e+09  1.286809e+08 -6.748454e+08  1.456361e+08  1.283345e+08   
2      -2.270361e+09 -5.640443e+08  2.275920e+09 -5.151486e+08 -5.727725e+08   
3      -7.780861e+09 -5.194079e+08  2.250640e+09 -4.932438e+08 -5.154629e+08   
4      -1.615361e+09  3.234764e+08 -1.172552e+09  3.014501e+08  3.453027e+08   
...              ...           ...           ...           ...           ...   
472675  2.765746e+09 -2.027933e+08  8.387241e+08 -1.627788e+08 -2.201881e+08   
472676 -7.023254e+09 -8.166839e+08  3.834215e+09 -7.631470e+08 -8.438692e+08   
472677 -6.564004e+09 -9.615312e+07  8.458989e+08 -1.012002e+08 -9.904161e+07   
472678  3.231996e+09  7.324260e+08 -3.153096e+09  6.994844e+08  7.481786e+08   
472679  7.925246e+09  5.554226e+08 -2.698596e+09  5.554717e+08  5.615639e+08   

                 P07  
0       5.795015e+08  
1       1.200615e+08  
2      -5.638794e+08  
3      -5.096987e+08  
4       3.307715e+08  
...              ...  
472675 -1.990811e+08  
472676 -8.059981e+08  
472677 -8.365675e+07  
472678  7.374126e+08  
472679  5.558047e+08  

[472680 rows x 11 columns]

In [17]:
from mne.decoding import CSP
from sklearn.model_selection import train_test_split, cross_val_score

In [18]:
# import numpy as np

# # สร้างตัวแปรเก็บข้อมูลที่เหลือ
# X_filtered = []
# y_filtered = []

# count_class_0 = 0
# max_class_0 = 20

# for i in range(len(y)):
#     if y[i] == 0 and count_class_0 < max_class_0:
#         # เพิ่มข้อมูล class 0 และเพิ่มจำนวน class 0 ที่เหลือ
#         X_filtered.append(X[i])
#         y_filtered.append(y[i])
#         count_class_0 += 1
#     elif y[i] != 0:
#         # เพิ่มข้อมูล class อื่นๆ ทั้งหมด
#         X_filtered.append(X[i])
#         y_filtered.append(y[i])

# # แปลงเป็น numpy array
# X_filtered = np.array(X_filtered)
# y_filtered = np.array(y_filtered)

# # ตรวจสอบขนาดของข้อมูลที่กรองแล้ว
# print("Filtered y shape:", y_filtered)
# print("Filtered X shape:", X_filtered)


In [19]:
# Get EEG data and events
X = mne_epochs.get_data()
y = mne_epochs.events[:, -1]
print(y.shape)
print(X.shape)
import numpy as np

# สร้างตัวแปรเก็บข้อมูลที่เหลือ
X_filtered = []
y_filtered = []

count_class_0 = 0
max_class_0 = 20

for i in range(len(y)):
    if y[i] == 0 and count_class_0 < max_class_0:
        # เพิ่มข้อมูล class 0 และเพิ่มจำนวน class 0 ที่เหลือ
        X_filtered.append(X[i])
        y_filtered.append(y[i])
        count_class_0 += 1
    elif y[i] != 0:
        # เพิ่มข้อมูล class อื่นๆ ทั้งหมด
        X_filtered.append(X[i])
        y_filtered.append(y[i])

# แปลงเป็น numpy array
X_filtered = np.array(X_filtered)
y_filtered = np.array(y_filtered)

# Initilize CSP
csp = CSP(n_components = 8, norm_trace = False)

# Fit CSP to data 
csp.fit(X_filtered, y_filtered)

# Visualize CSP patterns
# csp.plot_patterns(mne_epochs.info)

(180,)
(180, 8, 2626)
Computing rank from data with rank=None
    Using tolerance 2.2e+03 (2.2e-16 eps * 8 dim * 1.2e+18  max singular value)
    Estimated rank (mag): 8
    MAG: rank 8 computed from 8 data channels with 0 projectors
Reducing data rank from 8 -> 8
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 2.3e+03 (2.2e-16 eps * 8 dim * 1.3e+18  max singular value)
    Estimated rank (mag): 8
    MAG: rank 8 computed from 8 data channels with 0 projectors
Reducing data rank from 8 -> 8
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 2.3e+03 (2.2e-16 eps * 8 dim * 1.3e+18  max singular value)
    Estimated rank (mag): 8
    MAG: rank 8 computed from 8 data channels with 0 projectors
Reducing data rank from 8 -> 8
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 2.3e+03 (2.2e-16 eps * 8 dim * 1.3e+18  max singular valu

C:\Users\Toey\AppData\Local\Temp\ipykernel_11412\1417578336.py:2: FutureWarning: The current default of copy=False will change to copy=True in 1.7. Set the value of copy explicitly to avoid this warning
  X = mne_epochs.get_data()


CSP({'component_order': 'mutual_info',
 'cov_est': 'concat',
 'cov_method_params': None,
 'log': None,
 'n_components': 8,
 'norm_trace': False,
 'rank': None,
 'reg': None,
 'transform_into': 'average_power'})

In [20]:
# Transform data into CSP space
X_transformed = csp.transform(X_filtered)
# print(X_transformed.shape)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y_filtered, test_size = 0.2, random_state = 42)
# print(X_test[0])
# print(X_test[1])
# print(X_test)
# print(X_train.shape)
# print(X_test.shape)
# # print(y_test.shape)
# # print(y_train.shape)
# print(X_test)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC 
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Create and fit the logistic regression model within a pipeline
clf = Pipeline([('LR', LogisticRegression())])
clf.fit(X_train, y_train)

# Predict and calculate accuracy
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
array_con = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")

# report = classification_report(y_test, y_pred, target_names=[f'Frequency {fre1} Hz', f'Frequency {fre2} Hz', f'Frequency {fre3} Hz', f'Frequency {fre4} Hz'])
report = classification_report(y_test, y_pred, target_names=['natural', f'Frequency {fre1} Hz', f'Frequency {fre2} Hz', f'Frequency {fre3} Hz', f'Frequency {fre4} Hz'])  
print(report)
print(array_con)


Accuracy: 0.14285714285714285
                 precision    recall  f1-score   support

        natural       0.30      1.00      0.46         3
 Frequency 8 Hz       0.00      0.00      0.00         5
Frequency 10 Hz       0.00      0.00      0.00         4
Frequency 12 Hz       0.00      0.00      0.00         5
Frequency 14 Hz       0.00      0.00      0.00         4

       accuracy                           0.14        21
      macro avg       0.06      0.20      0.09        21
   weighted avg       0.04      0.14      0.07        21

[[3 0 0 0 0]
 [2 0 1 0 2]
 [0 0 0 0 4]
 [3 1 0 0 1]
 [2 2 0 0 0]]


C:\Users\Toey\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Toey\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Toey\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

In [22]:
from sklearn.svm import SVC 

clf = Pipeline([('SVM', SVC(kernel='linear'))])  
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

report = classification_report(y_test, y_pred, target_names=['natural', f'Frequency {fre1} Hz', f'Frequency {fre2} Hz', f'Frequency {fre3} Hz', f'Frequency {fre4} Hz'])  # adjust target names accordingly
print(report)

Accuracy: 0.2857142857142857
                 precision    recall  f1-score   support

        natural       0.30      1.00      0.46         3
 Frequency 8 Hz       0.00      0.00      0.00         5
Frequency 10 Hz       0.50      0.25      0.33         4
Frequency 12 Hz       0.00      0.00      0.00         5
Frequency 14 Hz       0.22      0.50      0.31         4

       accuracy                           0.29        21
      macro avg       0.20      0.35      0.22        21
   weighted avg       0.18      0.29      0.19        21



C:\Users\Toey\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Toey\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Toey\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is",

In [23]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

clf = Pipeline([('LDA', LDA())])
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

# print(len(X_test))
# print(X_train)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

report = classification_report(y_test, y_pred, target_names=['natural', f'Frequency {fre1} Hz', f'Frequency {fre2} Hz', f'Frequency {fre3} Hz', f'Frequency {fre4} Hz']) 
print(report)

Accuracy: 0.14285714285714285
                 precision    recall  f1-score   support

        natural       0.33      1.00      0.50         3
 Frequency 8 Hz       0.00      0.00      0.00         5
Frequency 10 Hz       0.00      0.00      0.00         4
Frequency 12 Hz       0.00      0.00      0.00         5
Frequency 14 Hz       0.00      0.00      0.00         4

       accuracy                           0.14        21
      macro avg       0.07      0.20      0.10        21
   weighted avg       0.05      0.14      0.07        21



In [24]:
# CSP-LDA pipeline

csp = CSP(n_components=4, log=True, norm_trace=False)
lda = LDA()

pipeline = Pipeline([('CSP', csp), ('LDA', lda)])

scores = cross_val_score(pipeline, X_filtered, y_filtered, cv=5)  # 5-fold cross-validation
print(scores)

Computing rank from data with rank=None
    Using tolerance 2e+03 (2.2e-16 eps * 8 dim * 1.1e+18  max singular value)
    Estimated rank (mag): 8
    MAG: rank 8 computed from 8 data channels with 0 projectors
Reducing data rank from 8 -> 8
Estimating covariance using EMPIRICAL
Done.


Computing rank from data with rank=None
    Using tolerance 2e+03 (2.2e-16 eps * 8 dim * 1.1e+18  max singular value)
    Estimated rank (mag): 8
    MAG: rank 8 computed from 8 data channels with 0 projectors
Reducing data rank from 8 -> 8
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 2e+03 (2.2e-16 eps * 8 dim * 1.1e+18  max singular value)
    Estimated rank (mag): 8
    MAG: rank 8 computed from 8 data channels with 0 projectors
Reducing data rank from 8 -> 8
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 2e+03 (2.2e-16 eps * 8 dim * 1.1e+18  max singular value)
    Estimated rank (mag): 8
    MAG: rank 8 computed from 8 data channels with 0 projectors
Reducing data rank from 8 -> 8
Estimating covariance using EMPIRICAL
Done.
Computing rank from data with rank=None
    Using tolerance 2e+03 (2.2e-16 eps * 8 dim * 1.1e+18  max singular value)
    Estimated rank (mag): 8

In [25]:
# from pylsl import StreamInlet, resolve_stream, StreamOutlet, StreamInfo

# print("looking for an EEG stream...")
# All_streams = resolve_stream()
# print(All_streams)

# Target_LSL = 'obci_eeg1' # Name of Openvibe LSL Streaming

# EEG_streams =[stream for stream in All_streams if stream.name() == Target_LSL]

# if len(EEG_streams) == 0:
#     print("Error: EEG stream not found")
#     exit()

# inlet = StreamInlet(EEG_streams[0])

# # num_channels = len(inlet.info().desc().channels)
# buffer_size = 100  # Number of samples to collect

# samples = []

# while len(samples) < buffer_size:
#     # Receive EEG Data from OpenBCI LSL Streaming
#     sample, timestamp = inlet.pull_sample()
#     if sample:
#         samples.append(sample)

# # Convert list of samples to numpy array
# samples_array = np.array(samples)

# # Reshape the array to (8, 100)
# reshaped_samples = samples_array.T  # Transpose to switch rows and columns

# # Ensure the shape is correct
# # assert reshaped_samples.shape == (num_channels, buffer_size)

# print("Shape of reshaped samples:", reshaped_samples.shape)

In [26]:
# channels =['FP1','FP2','C3','C4','T5','T6','O1','O2'] #Set your target EEG channel name
# info = mne.create_info(
#     ch_names= channels,
#     ch_types= ['eeg']*len(channels),
#     sfreq= 250 #OpenBCI Frequency acquistion
# )
# # Create MNE rawarray
# raw_mne = mne.io.RawArray(reshaped_samples, info, verbose=False)

In [27]:
# reshaped_data = raw_mne.get_data()

# # Add an additional dimension at the beginning with size 1
# reshaped_data = np.expand_dims(reshaped_data, axis=0)
# # print(reshaped_data.shape)
# # print(reshaped_data)

In [28]:
# duplicated_data = np.tile(reshaped_data, (2, 1, 1))
# concatenated_data = np.concatenate([duplicated_data, duplicated_data], axis=2)
# X = concatenated_data
# y = np.array([0,1])
# print(concatenated_data.shape)
# # print(len(X))
# # print(len(y))

# # Initilize CSP
# csp = CSP(n_components = 4, norm_trace = False)

# # # Fit CSP to data 
# csp.fit(X, y)

In [29]:
# X_transformed = csp.transform(X)
# y_pred = clf.predict(X_transformed)
# print(y_pred)