In [46]:
from scipy.io import loadmat
import pandas as pd

# โหลดข้อมูลจากไฟล์ .mat
mat_data = loadmat('C:/Users/Toey/Desktop/final_ssvep/For_use/P01_Ses6.mat')

In [47]:
import numpy as np

# ตรวจสอบ keys ทั้งหมดที่อยู่ใน dictionary
print(mat_data.keys())

# ตรวจสอบขนาดของข้อมูลในแต่ละ key
for key in mat_data.keys():
    print(f"Key: {key}, Shape: {np.shape(mat_data[key])}")


dict_keys(['__header__', '__version__', '__globals__', 'data_ses6'])
Key: __header__, Shape: ()
Key: __version__, Shape: ()
Key: __globals__, Shape: (0,)
Key: data_ses6, Shape: (10, 284113)


In [48]:
data = mat_data['data_ses6']
print(data)

[[ 0.00000000e+00  1.95312500e-03  3.90625000e-03 ...  5.54902344e+02
   5.54904297e+02  5.54906250e+02]
 [ 0.00000000e+00  1.38015457e+02  6.26481384e+02 ... -8.07995701e+00
  -8.54723072e+00 -1.03283834e+01]
 [ 0.00000000e+00 -5.61666756e+01 -2.73690887e+02 ... -1.06311560e+01
  -1.17711391e+01 -1.16142817e+01]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  1.11214130e+07
   1.11214130e+07  1.11214130e+07]]


In [49]:
df = pd.DataFrame(data.T, columns=["timestamps", "PO3", "POz", "PO4", "O1", "Oz", "O2", "triggers", "stimulation_periods", "decoder_outputs"])

# บันทึก DataFrame เป็นไฟล์ CSV
df.to_csv('data6.csv', index=False)

In [52]:
data_ses1 = mat_data['data_ses1']

# ดึงข้อมูลจากแต่ละแถว
timestamps = data_ses1[0]
channels = data_ses1[1:7]  # ช่อง PO3, POz, PO4, O1, Oz, O2
triggers = data_ses1[7]
processed_triggers = data_ses1[8]
decoder_outputs = data_ses1[9]

# ตัวอย่างการแสดงข้อมูล
print("Timestamps:")
print(timestamps)

print("\nChannels:")
print(channels)

print("\nTriggers:")
print(triggers)

print("\nProcessed Triggers:")
print(processed_triggers)

print("\nDecoder Outputs:")
print(decoder_outputs)

# ตัวอย่างการดึงข้อมูลจากแต่ละแถว
# เช่นการดึงเวลา timestamps ของแต่ละ trial
trial_timestamps = timestamps[0]

# เช่นการดึงข้อมูลจากช่อง PO3
po3_data = channels[0]

# เช่นการดึงข้อมูล triggers ของแต่ละ trial
trial_triggers = triggers[0]

# เช่นการดึงข้อมูล triggers ที่ถูกประมวลผลแล้ว
processed_trial_triggers = processed_triggers[0]

# เช่นการดึงผลลัพธ์จาก decoder ใน trial แรก
first_trial_decoder_output = decoder_outputs[0]


Timestamps:
[0.00000000e+00 1.95312500e-03 3.90625000e-03 ... 5.85152344e+02
 5.85154297e+02 5.85156250e+02]

Channels:
[[-7.40584656e+02 -3.45017407e+03 -6.28383057e+03 ... -1.94221573e+01
  -2.17068462e+01 -2.42440186e+01]
 [-1.12930641e+02 -5.28620850e+02 -9.72410278e+02 ... -2.76178303e+01
  -2.89141312e+01 -2.89518375e+01]
 [-7.67404236e+02 -3.58401367e+03 -6.55457227e+03 ... -2.92370243e+01
  -3.32141495e+01 -3.50372581e+01]
 [-1.76710449e+02 -8.17160034e+02 -1.46586597e+03 ... -4.89260721e+00
  -8.33162594e+00 -1.01312284e+01]
 [-3.25318512e+02 -1.52469690e+03 -2.81906616e+03 ... -3.78846207e+01
  -3.97624664e+01 -4.04456062e+01]
 [-7.34667908e+02 -3.44597412e+03 -6.36165967e+03 ...  1.54224777e+02
   1.48576523e+02  1.46825607e+02]]

Triggers:
[0. 0. 0. ... 0. 0. 0.]

Processed Triggers:
[0. 0. 0. ... 0. 0. 0.]

Decoder Outputs:
[      0.       0.       0. ... 5050505. 5050505. 5050505.]
